"""
# Configuration

We try to load `software_modules.wifi`, and then test the module
to see if the resource is available, cf.: `if devices.wifi`. And use the module's:

    .inet # (aka. wifi.radio or ethernet....)
    .connected() # we expect this to have the side-effect of connecting if possible

## hostname

You can provide a hostname in settings.toml:

    # a str.format() template. Params are `envhostname_or_uid` and `device_uid`
    CIRCUITPY_Hostname="myhostname" # .local will be appended for you
    OR
    CIRCUITPY_Hostname="myhostname:80" # with port, .local will be appended for you

if you don't, the hostname will be from initialize()

You can also set the hostname programmatically after `import` (see **Usage**).

## mDNS record

The default is to advertise as a http server, port 80 (`_http._tcp`). **NB.**: The adafruit "web" workflow
will use port 80 if you configure the appropriate entry in settings.toml.

You can set that programatically...
"""

# Detect resource: wifi, or other inet

try:
    import software_modules.wifi as inet_lan
except ImportError as e:
    if not str(e).endswith("'software_modules.wifi'"):
        raise e
    inet_lan = None

if not inet_lan:
    print("can't mdns: no wifi module")
    sys.modules[__name__] = None

# Have a module, and presumably hardware
# We may not have a connection though!

else:
    import os,sys
    import re

    # FIXME: fallback if no built-in mdns?
    try:
        import mdns
    except ImportError as e:
        if not str(e).endswith("'mdns'"):
            raise e
        mdns = None

    if not mdns:
        print("can't mdns: no mdns module (built-in)")
        sys.modules[__name__] = None

    else:
        print(f"mdns supported")

        from software_modules import every
        Every = every.Every

        DEBUG = False # verbosity
        Hostname = os.getenv("CIRCUITPY_Hostname", None)

        if Hostname is not None and (m:=re.search(r'(.+):(\d+)$', Hostname)):
            Hostname = m.group(1)
            Port = int(m.group(2))
        else:
            Port = 80
        if Hostname:
            print(f"Hostname from settings.toml CIRCUITPY_Hostname: {Hostname}.local")
        RECORD = { 'service_type' : "_http", 'protocol' : "_tcp", 'port' : Port }
        mdns_server = None

        readvertise_period = Every(60) # << mDNS TTL. and advertise immediately

        def _startup(n, wifi_enabled):
            global first_time, mdns_server
            if wifi_enabled:
                #print("mdns advertise...")
                mdns_server = mdns.Server(inet_lan.wifi_module.inet)
                first_time = True # force immediate
            else:
                if mdns_server:
                    mdns_server.deinit()
        inet_lan.wifi_module.subscribe( _startup )

        first_time = True
        def advertise():
            global first_time

            # mDNS records have a ttl, commonly 120 seconds.
            # Apparently the mDNS implementation on ESP readvertises for us
            # circuitpython 9 on the feather esp seems to be 120 seconds
            if inet_lan.wifi_module.is_connected() and (first_time or readvertise_period()) and Hostname is not None:
                    mdns_server.hostname = Hostname
                    # FIXME: default port is 5000, make chooseable?
                    # This is the "proper" mDNS record for a web-server entry
                    # Windows apparently ONLY pays attention to A and AAAA records
                    # which are generated by this advertisement (and windows has no built in mDNS browser)
                    mdns_server.advertise_service(**RECORD)
                    if first_time or DEBUG:
                        port_part = (':'+str(RECORD['port'])) if 'port' in RECORD else ''
                        scheme = RECORD['service_type'][1:] # strip _
                        print(f"mdns as {scheme}://{mdns_server.hostname}.local{port_part}")
                        first_time = False

        def update():
            advertise()

        def initialize(hostname, port=80):
            """The caller can provide a hostname
                it is only used if settings.toml CIRCUITPY_Hostname is absent
            """
            global Hostname, first_time
            if hostname is not None and Hostname is None:
                Hostname = hostname
                print(f"New hostname: {Hostname}.local")
            first_time = True # force readvertise
            RECORD['port']  = port
